server:
  port: 9098

spring:

  data:
    mongodb:
      database: MovieService


        # uri: mongodb+srv://shyam130701:shyam@shyamcluster.wfbvgmu.mongodb.net/MovieService
      host: localhost
      port: 27017
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  kafka:
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.LongSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      bootstrap-servers: localhost:9092
#    admin:
#      properties:
#        bootstrap.servers : localhost:9092
#
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: movie-groupId
#      bootstrap-servers: localhost:9092

